apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tridorian-labs
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/tridorian-taylor-sandbox/cloud-run-source-deploy/tridorian-labs:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 15
  traffic:
    - percent: 100
      latestRevision: true
